# This is a basic workflow to help you get started with Actions

name: Lazh-Validator Library CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'
    paths:
      - 'projects/lazh-validator/**'
      - '.github/workflows/Lazh-Validator-Lib-CI.yml'
  pull_request:
    branches:
      - 'develop'
    paths:
      - 'projects/lazh-validator/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          node-version: 10.x

    # Runs a single command using the runners shell
    - name: Install Dependencies
      run: npm install

    - name: Test Library
      run: npm run test-headless lazh-validator

    - name: Build Library
      if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' }}
      run: npm run build lazh-validator -- --prod

    - name: Set To Publish Directory
      if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}      
      run: cd ./dist/lazh-validator  

    - name: Publish Library To NPM
      id: publish      
      if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      uses: JS-DevTools/npm-publish@v1
      with:
          token: ${{ secrets.NPM_TOKEN }}

    - if: steps.publish.type != 'none'
      run: |
        echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
        
    # - name: Publish Library To Github
    #   if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    #   id: gprpublish
    #   with:
    #       node-version: 10.x
    #       registry-url: https://npm.pkg.github.com/
    #   run: npm publish
    #   env:
    #       NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && steps.gprpublish.type != 'none' }}
    #   run: |
    #     echo "Github Version changed: ${{ steps.gprpublish.outputs.old-version }} => ${{ steps.gprpublish.outputs.version }}"
